### PR TITLE
WA: Support JWTs as Access Tokens in the configuration/console

### PR DESCRIPTION
**Pull request by mmoayyed**
Requires #279

### CODE REVIEW

**Comment by ilgrosso** [comment]
@mmoayyed would it be possible to remove the changes already submitted in #279 ? I don't quite realize what this PR is for.
Thanks!

**Comment by mmoayyed** [comment]
I think the base branch I started off with was based on #279 . So once that is merged, then the "extra changes" here would automatically go away. If that PR is not merged/accepted, then I can surely rebase on top of the current master branch. The idea of this PR is to allow console to support the "JWT as Access Tokens" configuration option for OIDC RPs, both in the UI and the underlying models/TOs.

**Comment by ilgrosso** [comment]
I see, thanks.

**Comment by mmoayyed** [comment]
Merged with upstream, extra changes are now gone. I'll wait to see CI confirm changes/tests.

**Review by ilgrosso — APPROVED** [review]

**Review by ilgrosso — APPROVED** [review]

**Pull request merged**
