### PR TITLE
SYNCOPE-1438

### PR DESCRIPTION
**Pull request by DmitriyBrashevets**

### CODE REVIEW

**Comment by ilgrosso** [comment]
@DmitriyBrashevets LGTM, but please:
1. submit your ICLA: http://syncope.apache.org/contributing#How_do_I_become_a_contributor_or_a_committer.3F
1. open an issue on JIRA about this improvement, and mention the issue number (e.g. `SYNCOPE-XXXX` in your commit message)

Thanks!

**Comment by Dmitriy333** [comment]
1. Sent my ICLA to root@apache.org.
2. Ticket in Jira https://issues.apache.org/jira/browse/SYNCOPE-1438

**Comment by ilgrosso** [comment]
Ah, I have seen your ICLA, and that you opened SYNCOPE-1438 - thanks!
Would it be possible to change your commit message to include the string `SYNCOPE-1438`?

**Comment by Dmitriy333** [comment]
Updated commit message

**Comment by ilgrosso** [comment]
Merged, thanks!

**Comment by ilgrosso** [comment]
FYI, I have also cherry-picked your commit into the `2_1_X` and `master` branches.

**Pull request merged**
