### PR TITLE
Correcting errors in the documentation

### PR DESCRIPTION
**Pull request by rohanjulka19**

### CODE REVIEW

**Comment by ilgrosso** [comment]
Thanks @rohanjulka19 I have just merged your contribution.
Please consider sending an [ICLA](http://syncope.apache.org/contributing.html#How_do_I_become_a_contributor_or_a_committer)

Few notes:
1. I had to rebase and squash your commits into one, please do this for your future contributions
1. You probably did not attempt to build the docs, as there was a typo on the first license line of `src/main/asciidoc/reference-guide/workingwithapachesyncope/cli/user.adoc` which was breaking the build - to build docs, follow instructions at http://syncope.apache.org/building.html#Building_documentation
1. Not sure why you have replaced 'behavior' with 'behaviour' everywhere, but I accepted the change anyway :-)

**Comment by rohanjulka19** [comment]
Thank you sir for accepting my contribution . I  will consider all the points you mentioned . I will be emailing my ICLA by tomorrow . I am new to GitHub so it will take time to understand it . Can you please tell me when the changes will reflect on the site .

**Comment by ilgrosso** [comment]
> Can you please tell me when the changes will reflect on the site.

I have already requested your changes to be published, but it seems that [the ASF CI](https://ci.apache.org/builders/syncope-2_0_X-docs) is somewhat stuck.
Once it will be restarted, you will find your changes published at https://ci.apache.org/projects/syncope/2_0_X/reference-guide.html

Finally, once the next stable release 2.0.8 will be out, the updated content will be published at the standard location https://syncope.apache.org/docs/reference-guide.html

**Comment by ilgrosso** [comment]
I see your changes now published, cool :-)

**Comment by rohanjulka19** [comment]
It feels good.  :D

**Pull request closed without merging**
