### PR TITLE
Feature/add new password never expires field

### PR DESCRIPTION
**Pull request by Dmitriy333**
- **mustChangePassword** field is not initialized when creating new user issue is fixed
- added  new field **passwordNeverExpires**

See for [Thread in Maling List]( https://lists.apache.org/list.html?user@syncope.apache.org) for details

### CODE REVIEW

**Comment by ilgrosso** [comment]
@Dmitriy333 as discussed via mail, about the proposed `passwordNeverExpires`, I don't see rationale for adding fields to the `SyncopeUser` entity; you can achieve the same purpose by simply defining a boolean Plain Schema.

About initially setting `changePwdDate` at user creation, please go ahead and open an issue on JIRA, then create a PR on with a commit message mentioning such issue, thanks.

**Comment by ilgrosso** [comment]
@Dmitriy333 if you plan to contribute, please also submit your ICLA as described in How_do_I_become_a_contributor_or_a_committer.3F

**Comment by ilgrosso** [comment]
No feedback for 5 days - @Dmitriy333 shall we close this PR?

**Comment by ilgrosso** [comment]
Closing, no feedback for 8 days in total.

**Comment by Dmitriy333** [comment]
@ilgrosso , sorry for the delay. I have to create Pull Request from the new account.
Created it here https://github.com/apache/syncope/pull/97

**Pull request closed without merging**
