### PR TITLE
Bumping year to 2020

### PR DESCRIPTION
**Pull request by coheigea**

### CODE REVIEW

**Comment by ilgrosso** [comment]
@coheigea thanks for reporting this!

There are, however, several `NOTICE` files in the source tree that should be amended as well.

Moreover, we'll need to do the same with branches `2_1_X` and `2_0_X`

**Comment by coheigea** [comment]
@ilgrosso I updated the PR to pick up the other NOTICE files

**Comment by ilgrosso** [comment]
@coheigea by looking at other years' similar commits I found the following file should be updated as well: 'src/site/site.xml`

**Comment by coheigea** [comment]
@ilgrosso Done! Could you backport to the older branches?

**Comment by ilgrosso** [comment]
@coheigea sure

**Pull request merged**
