### PR TITLE
[SYNCOPE-1484]: syncope-ide-netbeans submodule fails to find netbeans dependency

### PR DESCRIPTION
**Pull request by mmoayyed**
Coordinates show that the current available release version is RELEASE111.

See https://issues.apache.org/jira/browse/SYNCOPE-1484
Related: https://issues.apache.org/jira/browse/SYNCOPE-1464

### CODE REVIEW

**Comment by ilgrosso** [comment]
Thanks for this OR @mmoayyed - please also remove the Netbeans repo in the root `pom.xml`, thanks.

**Comment by mmoayyed** [comment]
Sure. Done.

**Comment by ilgrosso** [comment]
Changes look good.

Not sure if this was happening with 8.2 deps too, but I received the following warnings during build:

```
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.api.annotations.common.proc.StaticResourceProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.windows.TopComponentProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.util.NbBundleProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.util.ServiceProviderProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.util.NamedServiceProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.awt.ActionProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.settings.convertors.ConvertorProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.intent.OpenUriHandlerProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.nodes.NodesAnnotationProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.editor.mimelookup.CreateRegistrationProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.filesystems.declmime.MIMEResolverProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.loaders.DataObjectFactoryProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.templates.TemplateProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.core.multiview.MultiViewProcessor' less than -source '11'
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.editor.lib2.EditorActionRegistrationProcessor' less than -source '11'
```

Finally, could you please also check if the Netbeans plugin is effectively working as expected? See http://syncope.apache.org/docs/2.1/getting-started.html#netbeans-ide-plugin for instructions.

Thanks!

**Comment by mmoayyed** [comment]
The plugin loads, installs and seems to work OK:

image

**Comment by ilgrosso** [comment]
Thanks @mmoayyed !

**Comment by ilgrosso** [comment]
@mmoayyed I backported your fix to:
* `2_1_X` as cf66e82a586d7148feb9dc8444ced9f28e4e173d
* `2_0_X` as 7e25619982861473d32ddb111da7fd21769c02b2

**Pull request merged**
