### PR TITLE
add edit button in site breadcrumb

### PR DESCRIPTION
**Pull request by hboutemy**
like done on https://maven.apache.org/

### CODE REVIEW

**Comment by ilgrosso** [comment]
Honestly, I don't like much the idea of ditching `gitbox.apache.org` for GitHub...

**Comment by ilgrosso** [comment]
@hboutemy let's discuss this proposed change in the dev@syncope mailing list, please

**Comment by hboutemy** [comment]
I'll have a look at your ML
I understand your relunctance to GH: yes, there is a choice to do to ease access to documentation source or keep everything pointing to Gitbox
don't hesiatte to drop this PR: there was not much effort in it

**Comment by ilgrosso** [comment]
Thank you.
I'll close this for now: feel free to reach up our dev mailing list to further discuss this topic, we can always re-open later.

**Pull request closed without merging**
