### PR TITLE
When importing users, cannot import more than 200 users.

### PR DESCRIPTION
**Pull request by tlnd-fcurvat**
Hi,
Found a bug when doing migration from syncope 1.2 to syncope 2.0.
Cannot migrate more than 200 users.
This "ugly" fix works for me, so i wanted to share.
Regards,

### CODE REVIEW

**Comment by ilgrosso** [comment]
Hi @tlnd-fcurvat thanks for this PR.

The fix looks good and I could merge it straight away, but I'd need first a couple of things:

1. you should submit an [ICLA](http://syncope.apache.org/contributing.html#How_do_I_become_a_contributor_or_a_committer)
1. you should open an issue on [JIRA](https://issues.apache.org/jira/projects/SYNCOPE) and possible reference its name (`SYNCOPE-XXXX`) in the commit message

Thanks!

**Comment by ilgrosso** [comment]
I have just seen SYNCOPE-1211 thanks!

**Comment by tlnd-fcurvat** [comment]
Quite busy, i will submit ICLA tomorrow.

**Comment by ilgrosso** [comment]
Thanks @tlnd-fcurvat !

**Comment by tlnd-fcurvat** [comment]
my pleasure :+1:

**Pull request closed without merging**
