### PR TITLE
SYNCOPE-1587: WA Web AuthN MFA support

### PR DESCRIPTION
**Pull request by mmoayyed**
https://issues.apache.org/jira/browse/SYNCOPE-1587

Adds baseline support for WA. Device registration and management APIs may be done in a separate pull request.

### CODE REVIEW

**Comment by ilgrosso** [comment]
@mmoayyed this PR looks good, but it seems there are issues with downloading transitive deps: https://travis-ci.org/github/apache/syncope/jobs/726236247#L433

**Comment by mmoayyed** [comment]
Thanks. I tweaked the pom publishing process a bit to include the required repos and looks like we are back in business here.

**Comment by mmoayyed** [comment]
This looks to be passing. CI failures seem random/phantom to me.

**Comment by ilgrosso** [comment]
@mmoayyed agree about CI

**Review by ilgrosso — CHANGES_REQUESTED** [review]
LGTM; only, it is missing the update for

```docker/wa/src/main/resources/wa.properties```

**Comment by mmoayyed** [comment]
Sure. I'll make the adjustment shortly.

**Pull request merged**
