### PR TITLE
Japanese translation

### PR DESCRIPTION
**Pull request by naofum**
Hello!

### CODE REVIEW

**Comment by mdisabatino** [comment]
Hi,
thanks for your contribution. 
I wanted to know if you already sent ICLA( Individual Contributors License Agreement) to become a contributor, if not you follow the guide you find at the following link[1]

[1] http://syncope.apache.org/contributing.html

**Comment by ilgrosso** [comment]
Thanks @naofum! We've been notified of your ICLA submission, please go ahead and open an issue on [JIRA](https://issues.apache.org/jira/projects/SYNCOPE) as stated above.

I've seen the PR is based on the `master` branch, but I believe it could be easily applied to the `2_0_X` branch too - so that the Admin Console could be release with Japanese support since next maintenance release 2.0.8.
I'll take a closer look in the coming days.

**Comment by ilgrosso** [comment]
You can take https://issues.apache.org/jira/browse/SYNCOPE-828 as reference

**Comment by ilgrosso** [comment]
Ah, I see it's also for Enduser UI, cool! :-)

**Comment by ilgrosso** [comment]
I have seen you opened SYNCOPE-1259, thanks!

**Comment by ilgrosso** [comment]
Thanks @naofum for your contribution!
I have applied this PR to branches `2_0_X` and `master`, hence Japanese translation will be available with next releases 2.0.8 and 2.1.0

Shortly, the [public demo](http://syncope.apache.org/demo.html) will be automatically updated; please, take a look to ensure that everything was picked up correctly.

**Pull request closed without merging**
