### PR TITLE
Modifiying documentation for netbeans IDE plugin

### PR DESCRIPTION
**Pull request by rohanjulka19**
When I downloaded the Netbeans plugin it was in zip format so I was not aware of what to do(silly me) . So I added a note which may help some users.

### CODE REVIEW

**Comment by ilgrosso** [comment]
There is no "If the downloaded plugin is in zip format", it *is* in zip format, please adjust.

Also, wrap the note into an asciidoctor's `[TIP]` block,

**Comment by rohanjulka19** [comment]
Yes sir

**Comment by rohanjulka19** [comment]
Is this ok 
"The downloaded plugin is in zip format , change its extension to .nbm otherwise you won't be able to use it with NetBeans"

**Comment by ilgrosso** [comment]
You don't need to "change its extension", you need to unzip it.

**Comment by rohanjulka19** [comment]
I unzipped the file  but was not able to add it as a plugin .

**Comment by ilgrosso** [comment]
Ah, correct it's .nbm indeed: why on earth you have downloaded as ZIP?

**Comment by ilgrosso** [comment]
Please close this PR, I don't see reasons to merge it.

**Comment by rohanjulka19** [comment]
I went to the link specified in the documentation and it downloads a zip file http://www.apache.org/dyn/closer.lua/syncope/2.0.7/syncope-ide-netbeans-2.0.7.nbm

**Comment by rohanjulka19** [comment]
Sorry for wasting your time

**Comment by ilgrosso** [comment]
np

**Pull request closed without merging**
